server:
  port: 8086

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/auth_db?options=-c%20TimeZone=UTC&sslmode=disable
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/api/auth/oauth2/callback/{registrationId}"

  mail:
    host: email-smtp.eu-north-1.amazonaws.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration-ms: 900000
    refresh-token-expiration-ms: 604800000

  frontend-url: ${FRONTEND_URL:http://localhost:3000}

  email:
    otp-expiry-minutes: 15
    from: noreply@zexxity.online

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

  instance:
    prefer-ip-address: true

logging:
  level:
    com.hacisimsek.auth: DEBUG
    org.springframework.security: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always